import { useEffect,useMemo,useState } from 'react';
import { Activity,Clock,Download,UserCheck,Wifi,XCircle } from 'lucide-react';
import { collection,limit,onSnapshot,orderBy,query } from 'firebase/firestore';
import * as XLSX from 'xlsx';
import { db } from '../../firebase';
import { useAuth } from '../../contexts/AuthContext';
import type { Professor } from '../../types';
import SmartCampusLogo from '../../components/SmartCampusLogo';

type Row=Record<string,unknown>&{id:string};
const card='rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg shadow-slate-950/20';
const button='inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 text-sm text-slate-200 transition hover:border-purple-500 hover:text-white';
const text=(value:unknown)=>String(value??'').trim();
const key=(value:unknown)=>text(value).toLowerCase();
const time=(value:unknown)=>{const timestamp=value as {toDate?:()=>Date};return timestamp?.toDate?.().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})||'â€”';};

export default function LiveProfessorDashboard(){
  const {userData}=useAuth();const professor=userData as Professor;
  const [students,setStudents]=useState<Row[]>([]),[attendance,setAttendance]=useState<Row[]>([]),[devices,setDevices]=useState<Row[]>([]),[sensors,setSensors]=useState<Row[]>([]);
  const [loaded,setLoaded]=useState({students:false,attendance:false}),[error,setError]=useState('');
  useEffect(()=>{console.log('Dashboard component file loaded');const fail=(source:string)=>(listenerError:Error)=>{console.error(`${source} listener error:`,listenerError);if(source==='Dashboard students'){setError('Unable to load dashboard data.');setLoaded(current=>({...current,students:true}));}if(source==='Dashboard attendance'){setError('Unable to load dashboard data.');setLoaded(current=>({...current,attendance:true}));}};const unsubscribeStudents=onSnapshot(collection(db,'students'),snapshot=>{setStudents(snapshot.docs.map(item=>({id:item.id,...item.data()})));setLoaded(current=>({...current,students:true}));},fail('Dashboard students'));const attendanceQuery=query(collection(db,'attendance'),orderBy('createdAt','desc'),limit(100));const unsubscribeAttendance=onSnapshot(attendanceQuery,snapshot=>{const records=snapshot.docs.map(item=>({id:item.id,...item.data()}));console.log('Attendance snapshot size:',snapshot.size);console.log('Attendance records:',records);setAttendance(records);setLoaded(current=>({...current,attendance:true}));},fail('Dashboard attendance'));const unsubscribeDevices=onSnapshot(collection(db,'devices'),snapshot=>setDevices(snapshot.docs.map(item=>({id:item.id,...item.data()}))),fail('ESP32 devices'));const unsubscribeSensors=onSnapshot(collection(db,'sensors'),snapshot=>setSensors(snapshot.docs.map(item=>({id:item.id,...item.data()}))),fail('Sensors'));return()=>{unsubscribeStudents();unsubscribeAttendance();unsubscribeDevices();unsubscribeSensors();};},[]);
  const activeStudents=useMemo(()=>students.filter(student=>key(student.status)==='active'||student.approved===true),[students]);
  const latestByStudent=useMemo(()=>{const latest=new Map<string,Row>();attendance.forEach(record=>{const keys=[key(record.studentUid),key(record.studentApogee)].filter(Boolean);if(keys.some(identity=>latest.has(identity)))return;keys.forEach(identity=>latest.set(identity,record));});return latest;},[attendance]);
  const latestStudentEvents=useMemo(()=>activeStudents.map(student=>latestByStudent.get(key(student.uid))||latestByStudent.get(key(student.apogee))).filter((record):record is Row=>Boolean(record)),[activeStudents,latestByStudent]);
  const presentRecords=latestStudentEvents.filter(record=>text(record.event).toUpperCase()==='ENTRY');const present=presentRecords.length;const absent=Math.max(activeStudents.length-present,0);const late=latestStudentEvents.filter(record=>text(record.event).toUpperCase()==='LATE').length;const percentage=activeStudents.length?Math.round(present/activeStudents.length*100):0;
  const currentRoom=useMemo(()=>{const rooms=new Map<string,number>();presentRecords.forEach(record=>{const room=text(record.room);if(room)rooms.set(room,(rooms.get(room)||0)+1);});return[...rooms.entries()].sort((a,b)=>b[1]-a[1])[0];},[presentRecords]);
  function exportAttendance(){const sheet=XLSX.utils.json_to_sheet(attendance.map(({id,...record})=>({ID:id,...record})));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Attendance');XLSX.writeFile(book,'professor-attendance.xlsx');}
  if(!loaded.students||!loaded.attendance)return <div className={`${card} py-12 text-center text-slate-400`}>Loading dashboard...</div>;
  if(error)return <div className="rounded-3xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300">{error}</div>;
  const metric=(label:string,value:string|number,icon:React.ReactNode,tone='text-purple-400 bg-purple-500/15')=><div className={card}><div className="flex items-center gap-3"><div className={`rounded-2xl p-3 ${tone}`}>{icon}</div><div><p className="text-sm text-slate-400">{label}</p><p className="text-2xl font-semibold text-white">{value}</p></div></div></div>;
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-start gap-3"><SmartCampusLogo size="md"/><div><p className="text-sm text-purple-400">Professor Portal</p><h1 className="text-3xl font-semibold text-white">Welcome, {professor?.firstName||'Professor'}</h1><p className="mt-1 text-sm text-slate-400">Live overview of your classes, attendance and connected classroom.</p></div></div><button className={button} onClick={exportAttendance}><Download size={16}/>Export attendance</button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric('Students present',present,<UserCheck size={20}/>, 'text-emerald-400 bg-emerald-500/15')}{metric('Absent students',absent,<XCircle size={20}/>, 'text-rose-400 bg-rose-500/15')}{metric('Late students',late,<Clock size={20}/>, 'text-amber-400 bg-amber-500/15')}{metric('Attendance',`${percentage}%`,<Activity size={20}/>)}</div>
  <div className="grid gap-6 xl:grid-cols-3"><section className={`${card} xl:col-span-2`}><h2 className="text-xl font-semibold text-white">Current session</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase text-slate-500">Course</p><p className="mt-1 text-white">Live RFID attendance</p></div><div><p className="text-xs uppercase text-slate-500">Classroom</p><p className="mt-1 text-white">{currentRoom?.[0]||'â€”'}</p></div><div><p className="text-xs uppercase text-slate-500">Occupancy</p><p className="mt-1 text-white">{currentRoom?`${currentRoom[1]} students`:'â€”'}</p></div></div></section><section className={card}><h2 className="text-xl font-semibold text-white">Connected systems</h2><div className="mt-4 space-y-3"><p className="flex justify-between text-sm text-slate-300"><span className="flex gap-2"><Wifi size={17}/>ESP32 status</span><span className="text-emerald-400">{devices.filter(device=>key(device.status)==='online').length}/{devices.length} online</span></p><p className="flex justify-between text-sm text-slate-300"><span className="flex gap-2"><Activity size={17}/>Sensors status</span><span className="text-cyan-400">{sensors.filter(sensor=>key(sensor.status)!=='offline').length}/{sensors.length} active</span></p></div></section></div>
  <section className={card}><h2 className="text-xl font-semibold text-white">Latest RFID scans</h2><div className="mt-4 space-y-2">{attendance.slice(0,10).map(record=><div key={record.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-800 bg-slate-950/50 px-4 py-3 text-sm"><div><span className="text-white">{text(record.studentName)||'Unknown card'}</span><span className="ml-2 text-xs text-slate-500">{text(record.studentApogee)||'â€”'}</span></div><span className={`rounded-full px-2 py-1 text-xs ${text(record.event).toUpperCase()==='ENTRY'?'bg-emerald-500/15 text-emerald-300':'bg-orange-500/15 text-orange-300'}`}>{text(record.event)||'â€”'}</span><span className="text-slate-400">{text(record.room)||'â€”'}</span><span className="font-mono text-purple-300">{text(record.rfidUID)||'â€”'}</span><span className="text-slate-400">{time(record.createdAt)}</span></div>)}{!attendance.length&&<div className="py-8 text-center text-sm text-slate-500">No RFID scans found.</div>}</div></section></div>;
}


