import { useEffect, useMemo, useState } from 'react';
import { collection, getDocs, onSnapshot, query, where } from 'firebase/firestore';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Clock, Download, Eye, Printer, Square, Plus } from 'lucide-react';
import { auth, db } from '../../firebase';
import { useAuth } from '../../contexts/AuthContext';

type Row = Record<string, any> & { id: string };
const card = 'rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg shadow-slate-950/20';
const input = 'rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 text-sm text-slate-200 outline-none focus:border-purple-500';
const button = 'inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 text-sm text-slate-200 transition hover:border-purple-500 hover:text-white disabled:cursor-not-allowed disabled:opacity-50';
const morocco = 'Africa/Casablanca';
const apiBase = 'https://smartcampus360-production.up.railway.app';
const date = (v: any) => { const d = v?.toDate?.() ?? (v ? new Date(v) : undefined); return d && !Number.isNaN(d.getTime()) ? new Intl.DateTimeFormat('fr-FR', { timeZone: morocco }).format(d) : '—'; };
const time = (v: any) => { if (typeof v === 'string') return v; const d = v?.toDate?.() ?? (v ? new Date(v) : undefined); return d && !Number.isNaN(d.getTime()) ? new Intl.DateTimeFormat('fr-FR', { timeZone: morocco, hour: '2-digit', minute: '2-digit' }).format(d) : '—'; };
const value = (row: Row | undefined, ...keys: string[]) => keys.map(k => row?.[k]).find(v => v !== undefined && v !== null && v !== '') ?? '';
const normalized = (v: unknown) => String(v ?? '').trim().toLowerCase();

function LiveClock() {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const id = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(id); }, []);
  return <div className="flex items-center gap-3 rounded-2xl border border-purple-500/20 bg-purple-500/10 px-4 py-3 text-sm"><Clock size={18} className="text-purple-300"/><div><p className="font-semibold text-white">{new Intl.DateTimeFormat('fr-FR', { timeZone: morocco }).format(now)}</p><p className="font-mono text-purple-200">{new Intl.DateTimeFormat('fr-FR', { timeZone: morocco, hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(now)}</p></div></div>;
}

export default function ProfessorAttendancePage() {
  const { currentUser, userData } = useAuth();
  const [sessions, setSessions] = useState<Row[]>([]); const [students, setStudents] = useState<Row[]>([]); const [records, setRecords] = useState<Row[]>([]);
  const [selected, setSelected] = useState<Row | null>(null); const [search, setSearch] = useState(''); const [filter, setFilter] = useState({ filiere: '', niveau: '', status: '' });
  const [form, setForm] = useState({ filiere: '', niveau: '', room: '' }); const [rooms, setRooms] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const professorId = currentUser?.uid || '';
  useEffect(() => { if (!professorId) return; return onSnapshot(query(collection(db, 'attendanceSessions'), where('professorId', '==', professorId)), s => setSessions(s.docs.map(d => ({ id: d.id, ...d.data() } as Row)).sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0))), e => setError(e.message)); }, [professorId]);
  useEffect(() => onSnapshot(collection(db, 'students'), s => setStudents(s.docs.map(d => ({ id: d.id, ...d.data() }))), e => setError(e.message)), []);
  useEffect(() => onSnapshot(collection(db, 'classrooms'), s => { const available = s.docs.map(d => String(value({ id: d.id, ...d.data() }, 'name', 'room', 'classroom')).trim()).filter(Boolean); setRooms([...new Set(available.length ? available : ['Amphi A'])].sort()); }, e => { setRooms(['Amphi A']); setError(e.message); }), []);
  const active = sessions.find(s => s.status === 'En cours' && s.room) || null;
  const displayed = selected || active;
  useEffect(() => { if (!displayed) { setRecords([]); return; } return onSnapshot(query(collection(db, 'attendance'), where('sessionId', '==', displayed.id)), s => setRecords(s.docs.map(d => ({ id: d.id, ...d.data() }))), e => setError(e.message)); }, [displayed?.id]);
  const filieres = useMemo(() => [...new Set(students.map(s => String(value(s, 'filiere', 'department', 'program'))).filter(Boolean))].sort(), [students]);
  const niveaux = useMemo(() => [...new Set(students.map(s => String(value(s, 'niveau', 'level', 'studyLevel'))).filter(Boolean))].sort(), [students]);
  const roster = useMemo(() => !displayed ? [] : students.filter(s => normalized(value(s, 'filiere', 'department', 'program')) === normalized(displayed.filiere) && normalized(value(s, 'niveau', 'level', 'studyLevel')) === normalized(displayed.niveau)), [students, displayed]);
  const reportRows = useMemo(() => roster.map(student => { const present = records.find(r => normalized(value(r, 'studentUid', 'studentId')) === normalized(value(student, 'uid', 'id')) || normalized(value(r, 'studentApogee')) === normalized(value(student, 'apogee'))); return { student, record: present, status: present ? 'Present' : 'Absent' }; }), [roster, records]);
  const filteredRows = reportRows.filter(r => (!search || `${value(r.student, 'firstName')} ${value(r.student, 'lastName')} ${value(r.student, 'apogee')}`.toLowerCase().includes(search.toLowerCase())) && (!filter.filiere || normalized(value(r.student, 'filiere', 'department', 'program')) === normalized(filter.filiere)) && (!filter.niveau || normalized(value(r.student, 'niveau', 'level')) === normalized(filter.niveau)) && (!filter.status || r.status === filter.status));
  const present = reportRows.filter(r => r.status === 'Present').length;
  async function sessionRequest(path: string, body: Record<string, unknown>) { const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error('Please sign in again to manage attendance sessions.'); const response = await fetch(`${apiBase}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'The session request failed.'); return result; }
  async function start() { if (!form.filiere || !form.niveau || !form.room || !professorId || active) return; setBusy(true); setError(''); try { const now = new Date(); await sessionRequest('/api/sessions/start', { date: new Intl.DateTimeFormat('fr-FR', { timeZone: morocco }).format(now), startTime: new Intl.DateTimeFormat('fr-FR', { timeZone: morocco, hour: '2-digit', minute: '2-digit' }).format(now), filiere: form.filiere, niveau: form.niveau, room: form.room, professorName: `${userData?.firstName || ''} ${userData?.lastName || ''}`.trim() || currentUser?.email || 'Professor' }); } catch (e: any) { setError(e.message || 'Could not start the session.'); } finally { setBusy(false); } }
  async function finish() { if (!active) return; setBusy(true); setError(''); try { await sessionRequest('/api/sessions/finish', { sessionId: active.id, endTime: new Intl.DateTimeFormat('en-GB', { timeZone: morocco, hour: '2-digit', minute: '2-digit' }).format(new Date()) }); } catch (e: any) { setError(e.message || 'Could not end the session.'); } finally { setBusy(false); } }
  async function pdf(session: Row) { const snapshot = session.id === displayed?.id ? null : await getDocs(query(collection(db, 'attendance'), where('sessionId', '==', session.id))); const sessionRecords = snapshot ? snapshot.docs.map(d => ({ id: d.id, ...d.data() } as Row)) : records; const sessionRoster = students.filter(s => normalized(value(s, 'filiere', 'department', 'program')) === normalized(session.filiere) && normalized(value(s, 'niveau', 'level', 'studyLevel')) === normalized(session.niveau)); const rows = sessionRoster.map(student => { const record = sessionRecords.find(r => normalized(value(r, 'studentUid', 'studentId')) === normalized(value(student, 'uid', 'id')) || normalized(value(r, 'studentApogee')) === normalized(value(student, 'apogee'))); return { student, record, status: record ? 'Present' : 'Absent' }; }); const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' }); const p = rows.filter(r => r.status === 'Present').length; pdf.setFillColor(88, 28, 135); pdf.rect(0, 0, 297, 24, 'F'); pdf.setTextColor(255); pdf.setFontSize(18); pdf.text('SMART CAMPUS 360', 14, 12); pdf.setFontSize(11); pdf.text('Professor Attendance Report', 14, 19); pdf.setTextColor(20); pdf.setFontSize(14); pdf.text('ATTENDANCE SESSION', 14, 35); pdf.setFontSize(10); pdf.text([`Date: ${session.date || date(session.createdAt)}`, `Start time: ${session.startTime || '—'}`, `End time: ${session.endTime || '—'}`, `Program: ${session.filiere}`, `Level: ${session.niveau}`, `Professor: ${session.professorName}`, `Room: ${session.room || '—'}`], 14, 43); pdf.text([`Enrolled students: ${rows.length}`, `Present: ${p}`, `Absent: ${rows.length - p}`], 150, 43); autoTable(pdf, { startY: 73, head: [['No.', 'Full name', 'Apogee', 'Program', 'Level', 'Entry', 'Exit', 'Status']], body: rows.map((r, i) => [i + 1, `${value(r.student, 'firstName')} ${value(r.student, 'lastName')}`, value(r.student, 'apogee') || '—', session.filiere, session.niveau, r.record ? time(value(r.record, 'entryTime', 'createdAt')) : '—', r.record ? time(value(r.record, 'exitTime')) : '—', r.status]), styles: { fontSize: 8, cellPadding: 2 }, headStyles: { fillColor: [88, 28, 135] }, didDrawPage: (d: { pageNumber: number }) => { pdf.setFontSize(8); pdf.text(`Generated on: ${date(new Date())} ${time(new Date())}  â€¢  Page ${d.pageNumber}`, 14, 205); } }); pdf.save(`session_${session.date || session.id}.pdf`); }
  function print(session: Row) { setSelected(session); window.setTimeout(() => window.print(), 0); }
  return <div className="space-y-6 print:space-y-0"><style>{`@media print { aside, nav, button, .no-print { display:none!important } body { background:white!important } main { padding:0!important } .print-report { display:block!important; color:#111!important; border:0!important; box-shadow:none!important } }`}</style><div className="no-print flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-purple-400">Professor Portal</p><h1 className="text-3xl font-semibold text-white">Attendance sessions</h1><p className="mt-1 text-sm text-slate-400">RFID attendance is grouped by session; sessions never mix dates.</p></div><LiveClock/></div>
    <section className={`${card} no-print`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-widest text-purple-300">ACTIVE SESSION</p>{active ? <div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>Date: <b className="text-white">{active.date || date(active.createdAt)}</b></p><p>Start time: <b className="text-white">{active.startTime}</b></p><p>Status: <b className="text-emerald-300">Active</b></p><p>Room: <b className="text-white">{active.room || 'Room unavailable'}</b></p><p>Program: <b className="text-white">{active.filiere}</b></p><p>Level: <b className="text-white">{active.niveau}</b></p></div> : <p className="mt-2 text-sm text-slate-400">No active session. Select a program, level, and room to start.</p>}</div><div className="flex flex-wrap gap-2"><select className={input} value={form.filiere} disabled={!!active} onChange={e => setForm({ ...form, filiere: e.target.value })}><option value="">Program</option>{filieres.map(x => <option key={x}>{x}</option>)}</select><select className={input} value={form.niveau} disabled={!!active} onChange={e => setForm({ ...form, niveau: e.target.value })}><option value="">Level</option>{niveaux.map(x => <option key={x}>{x}</option>)}</select><select className={input} value={form.room} disabled={!!active} onChange={e => setForm({ ...form, room: e.target.value })}><option value="">Room</option>{rooms.map(x => <option key={x}>{x}</option>)}</select><button className={button} disabled={busy || !!active || !form.filiere || !form.niveau || !form.room} onClick={start}><Plus size={16}/>New session</button><button className={button} disabled={busy || !active} onClick={finish}><Square size={15}/>End session</button></div></div></section>
    {error && <div className="no-print rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</div>}
    {displayed && <section className={`${card} print-report`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">{selected ? 'Session details' : 'Current session attendance'}</h2><p className="text-sm text-slate-400">{displayed.filiere} · {displayed.niveau} · {displayed.room || 'Room unavailable'} · {displayed.date || date(displayed.createdAt)}</p></div><div className="no-print flex gap-2"><button className={button} onClick={() => pdf(displayed)}><Download size={15}/>PDF</button><button className={button} onClick={() => print(displayed)}><Printer size={15}/>Print</button></div></div><div className="no-print mt-4 grid gap-2 md:grid-cols-4"><input className={input} value={search} onChange={e => setSearch(e.target.value)} placeholder="Search students"/><select className={input} value={filter.filiere} onChange={e => setFilter({ ...filter, filiere: e.target.value })}><option value="">All programs</option>{filieres.map(x => <option key={x}>{x}</option>)}</select><select className={input} value={filter.niveau} onChange={e => setFilter({ ...filter, niveau: e.target.value })}><option value="">All levels</option>{niveaux.map(x => <option key={x}>{x}</option>)}</select><select className={input} value={filter.status} onChange={e => setFilter({ ...filter, status: e.target.value })}><option value="">All statuses</option><option>Present</option><option>Absent</option></select></div><p className="mt-4 text-sm text-slate-300">Summary: <b>{reportRows.length}</b> enrolled · <b className="text-emerald-300">{present}</b> present · <b className="text-rose-300">{reportRows.length - present}</b> absent</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['No.','Full name','Apogee','Program','Level','Entry','Exit','Status'].map(x => <th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{filteredRows.map((r, i) => <tr key={r.student.id} className="border-t border-slate-800"><td className="px-3 py-3">{i + 1}</td><td className="px-3 py-3 font-medium text-white">{value(r.student, 'firstName')} {value(r.student, 'lastName')}</td><td className="px-3 py-3">{value(r.student, 'apogee')}</td><td className="px-3 py-3">{displayed.filiere}</td><td className="px-3 py-3">{displayed.niveau}</td><td className="px-3 py-3">{r.record ? time(value(r.record, 'entryTime', 'createdAt')) : '—'}</td><td className="px-3 py-3">{r.record ? time(value(r.record, 'exitTime')) : '—'}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 ${r.status === 'Present' ? 'bg-emerald-500/15 text-emerald-300' : 'bg-rose-500/15 text-rose-300'}`}>{r.status}</span></td></tr>)}</tbody></table></div></section>}
    <section className={`${card} no-print`}><h2 className="text-xl font-semibold text-white">Session history</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['Date','Room','Program','Level','Start','End','Status','Present','Actions'].map(x => <th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{sessions.map(s => <tr key={s.id} className="border-t border-slate-800"><td className="px-3 py-3">{s.date || date(s.createdAt)}</td><td className="px-3 py-3">{s.room || 'Room unavailable'}</td><td className="px-3 py-3">{s.filiere}</td><td className="px-3 py-3">{s.niveau}</td><td className="px-3 py-3">{s.startTime}</td><td className="px-3 py-3">{s.endTime || '—'}</td><td className="px-3 py-3">{s.status === 'En cours' ? 'Active' : s.status === 'Terminée' ? 'Completed' : s.status}</td><td className="px-3 py-3">{s.id === displayed?.id ? present : 'View report'}</td><td className="flex gap-2 px-3 py-3"><button className={button} onClick={() => setSelected(s)}><Eye size={14}/>View</button><button className={button} onClick={() => { setSelected(s); window.setTimeout(() => pdf(s), 0); }}><Download size={14}/>PDF</button><button className={button} onClick={() => print(s)}><Printer size={14}/>Print</button></td></tr>)}</tbody></table>{!sessions.length && <p className="py-8 text-center text-sm text-slate-500">No sessions created.</p>}</div></section>
  </div>;
}
