import { useEffect, useMemo, useState } from 'react';
import { collection, limit, onSnapshot, orderBy, query } from 'firebase/firestore';
import { AlertTriangle, Building2, Cpu, GraduationCap, Radio, UserCheck, Users } from 'lucide-react';
import { db } from '../../firebase';
import { useAuth } from '../../contexts/AuthContext';
import type { Admin } from '../../types';
import SmartCampusLogo from '../../components/SmartCampusLogo';

type Row={id:string;[key:string]:any};
const time=(value:any)=>value?.toDate?.().getTime?.() ?? ((value?.seconds ?? 0) * 1000);
export default function AdminDashboard(){const {userData}=useAuth();const admin=userData as Admin;const [students,setStudents]=useState<Row[]>([]),[professors,setProfessors]=useState<Row[]>([]),[rooms,setRooms]=useState<Row[]>([]),[devices,setDevices]=useState<Row[]>([]),[attendance,setAttendance]=useState<Row[]>([]),[loaded,setLoaded]=useState(0),[errors,setErrors]=useState<string[]>([]);
  useEffect(()=>{const listen=(name:string,target:any,setter:(v:Row[])=>void)=>onSnapshot(target,(s:any)=>{setter(s.docs.map((d:any)=>({id:d.id,...d.data()})));setLoaded(v=>v+1)},e=>{console.error(`${name} listener error:`,e);setErrors(v=>[...v,name]);setLoaded(v=>v+1)});const stops=[listen('students',collection(db,'students'),setStudents),listen('professors',collection(db,'professors'),setProfessors),listen('classrooms',collection(db,'classrooms'),setRooms),listen('devices',collection(db,'devices'),setDevices),listen('attendance',query(collection(db,'attendance'),orderBy('createdAt','desc'),limit(100)),setAttendance)];return()=>stops.forEach(stop=>stop())},[]);
  const state=useMemo(()=>{const latest=new Map<string,Row>();attendance.forEach(r=>{const key=r.studentUid||r.studentApogee;if(key&&!latest.has(key))latest.set(key,r)});const present=[...latest.values()].filter(r=>r.event==='ENTRY').length;const online=devices.filter(d=>d.online===true&&Date.now()-time(d.lastSeenAt)<5*60_000).length;return{present,absent:Math.max(0,students.filter(s=>s.status==='active').length-present),online,pending:students.filter(s=>s.status==='pending').length}},[attendance,devices,students]);
  const cards=[['Total Students',students.length,Users,'text-cyan-400'],['Total Professors',professors.length,GraduationCap,'text-purple-400'],['Present Students',state.present,UserCheck,'text-emerald-400'],['Absent Students',state.absent,AlertTriangle,'text-rose-400'],['Active Rooms',rooms.filter(r=>r.active!==false).length,Building2,'text-amber-400'],['Online Devices',state.online,Cpu,'text-cyan-400'],['Pending Registrations',state.pending,Radio,'text-amber-400']];
  return <div className="space-y-6"><div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><div className="mb-3"><SmartCampusLogo size="md" /></div><p className="text-sm text-rose-400">Administrator Portal</p><h1 className="text-2xl font-semibold text-white">{admin?.firstName} {admin?.lastName}</h1><p className="text-sm text-slate-400">Live campus overview</p></div>{errors.length>0&&<div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-rose-300">Unable to load: {errors.join(', ')}.</div>}{loaded<5?<div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 text-slate-400">Loading campus data...</div>:<><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon,tone]:any)=><div key={label} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><div className="flex items-center gap-3"><div className={`rounded-2xl bg-slate-950 p-3 ${tone}`}><Icon size={20}/></div><div><p className="text-sm text-slate-400">{label}</p><p className="text-2xl font-semibold text-white">{value}</p></div></div></div>)}</div><div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><h2 className="mb-4 text-xl font-semibold text-white">Latest RFID Scans</h2>{attendance.length===0?<p className="text-slate-500">No RFID scans found.</p>:<div className="space-y-2">{attendance.slice(0,10).map(r=><div key={r.id} className="flex flex-wrap justify-between gap-2 rounded-2xl border border-slate-800 bg-slate-950/60 px-4 py-3"><span className="text-white">{r.studentName||r.studentApogee||'â€”'}</span><span className={r.event==='ENTRY'?'text-emerald-400':'text-orange-400'}>{r.event||'â€”'}</span><span className="text-slate-400">{r.room||'â€”'} Â· {r.createdAt?.toDate?.().toLocaleString()||'â€”'}</span></div>)}</div>}</div></>}</div>}


